/**
 * @file      hardware.h (180.ARM_Peripherals/Sources/hardware.h)
 *
 * Main header file for USBDM library.
 * Generated code is included via this file.
 *
 * @version  V4.12.1.270
 * @date     1 December 2021
 */

/*
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#ifndef INCLUDE_USBDM_HARDWARE_H_
#define INCLUDE_USBDM_HARDWARE_H_

#include "error.h"
#include "pin_mapping.h"
#include "delay.h"
#include "console.h"

#include "gpio.h"
#include "adc.h"
#include "spi.h"
#include "cmp.h"


namespace USBDM {

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
extern void mapAllPins();

/// Vbdm
typedef const Adc0::Channel<12>                              TVdd_Measure;                                 // PTB2(p37)

typedef const Adc0::Channel<19>                              Identify;                                     // ADC0_DM0(p10)

/// CMP, Analogue Comparator
typedef const Cmp0                                           TVdd_Monitor;                                 

/// Vbdm
typedef const Cmp0::Pin<Cmp0::Input_Ptc7>                    TVdd_Mon;                                     // PTC7(p52)

/// TPa2
typedef const GpioTable_T<GpioBInfo, 1, ActiveHigh>          TPa2;                                         // PTB1(p36)

/// TPa1
typedef const GpioTable_T<GpioBInfo, 0, ActiveHigh>          TPa1;                                         // PTB0(p35)

/// TVddLed
typedef const GpioTable_T<GpioBInfo, 3, ActiveHigh>          TVdd_Led;                                     // PTB3(p38)

/// RST_DIR
typedef const GpioTable_T<GpioCInfo, 0, ActiveHigh>          Reset_Dir;                                    // PTC0(p43)

/// RST_IO
typedef const GpioTable_T<GpioCInfo, 1, ActiveHigh>          Reset_IO;                                     // PTC1(p44)

/// SWD_EN
typedef const GpioTable_T<GpioCInfo, 4, ActiveHigh>          Swd_Enable;                                   // PTC4(p49)

/// Vdd_En
typedef const GpioTable_T<GpioDInfo, 1, ActiveHigh>          TVdd_Enable;                                  // PTD1(p58)

/// USB_LED
typedef const GpioTable_T<GpioDInfo, 7, ActiveHigh>          Usb_Led;                                      // PTD7(p64)

/// Vdd_Flt
typedef const GpioTable_T<GpioDInfo, 0, ActiveHigh>          TVdd_Fault;                                   // PTD0(p57)

/// SPI, Serial Peripheral Interface
typedef Spi0                                                 SwdSpi;                                       

} // End namespace USBDM

#endif /* INCLUDE_USBDM_HARDWARE_H_ */
