/**
 * @file      hardware.cpp (generated from MK20D5.usbdmHardware)
 * @version   1.3.0
 * @brief     Pin initialisation for MK20DX128VLF5
 *
 * *****************************
 * *** DO NOT EDIT THIS FILE ***
 * *****************************
 *
 * This file is generated automatically.
 * Any manual changes will be lost.
 */

#include "hardware.h"

/**
 * Namespace enclosing USBDM classes
 */
namespace USBDM {

/**
 * @addtogroup USBDM_Group USBDM Peripheral Interface
 * @brief Hardware Peripheral Interface and library
 * @{
 */

/**
 * Startup code for C++ classes
 */
extern "C" void __attribute__((constructor)) cpp_initialise() {
   if constexpr (MapAllPinsOnStartup) {
      mapAllPins();
   }
}

// No user object definitions found

/**
 * Map all configured pins to peripheral signals.
 *
 * PCRs of allocated pins are set according to settings in Configure.usbdmProject
 *
 * @note Only the lower 16-bits of the PCR registers are initialised
 */
void mapAllPins() {
#if true


#endif


#if defined(PCC_PCCn_CGC_MASK)
   PCC->PCC_PORTA = PCC_PCCn_CGC_MASK;
   PCC->PCC_PORTB = PCC_PCCn_CGC_MASK;
   PCC->PCC_PORTC = PCC_PCCn_CGC_MASK;
   PCC->PCC_PORTD = PCC_PCCn_CGC_MASK;
   PCC->PCC_PORTE = PCC_PCCn_CGC_MASK;
#else
   enablePortClocks(PORTA_CLOCK_MASK|PORTB_CLOCK_MASK|PORTC_CLOCK_MASK|PORTD_CLOCK_MASK|PORTE_CLOCK_MASK);
#endif

   PORTA->GPCLR = ForceLockedPins|0x8200UL|PORT_GPCLR_GPWE(0x0006UL);
   PORTA->GPCLR = ForceLockedPins|0x8700UL|PORT_GPCLR_GPWE(0x0009UL);
   PORTB->GPCLR = ForceLockedPins|0x8000UL|PORT_GPCLR_GPWE(0x0004UL);
   PORTB->GPCLR = ForceLockedPins|0x8100UL|PORT_GPCLR_GPWE(0x000BUL);
   PORTC->GPCLR = ForceLockedPins|0x0200UL|PORT_GPCLR_GPWE(0x0064UL);
   PORTC->GPCLR = ForceLockedPins|0x0400UL|PORT_GPCLR_GPWE(0x0008UL);
   PORTC->GPCLR = ForceLockedPins|0x8000UL|PORT_GPCLR_GPWE(0x0080UL);
   PORTC->GPCLR = ForceLockedPins|0x8100UL|PORT_GPCLR_GPWE(0x0013UL);
   PORTD->GPCLR = ForceLockedPins|0x0200UL|PORT_GPCLR_GPWE(0x0008UL);
   PORTD->GPCLR = ForceLockedPins|0x0400UL|PORT_GPCLR_GPWE(0x0050UL);
   PORTD->GPCLR = ForceLockedPins|0x8100UL|PORT_GPCLR_GPWE(0x0083UL);
   PORTE->GPCLR = ForceLockedPins|0x8300UL|PORT_GPCLR_GPWE(0x0003UL);

   if constexpr (ForceLockoutUnbondedPins) {
      PORTA->GPCLR = PinLock_Locked |0x0000UL|PORT_GPCLR_GPWE(0xCFC0UL); // Lockout unavailable pins
      PORTA->GPCHR = PinLock_Locked |0x0000UL|PORT_GPCHR_GPWE(0xFFF3UL); // Lockout unavailable pins
      PORTB->GPCLR = PinLock_Locked |0x0000UL|PORT_GPCLR_GPWE(0xFFF0UL); // Lockout unavailable pins
      PORTB->GPCHR = PinLock_Locked |0x0000UL|PORT_GPCHR_GPWE(0xFFF0UL); // Lockout unavailable pins
      PORTC->GPCLR = PinLock_Locked |0x0000UL|PORT_GPCLR_GPWE(0xF000UL); // Lockout unavailable pins
      PORTC->GPCHR = PinLock_Locked |0x0000UL|PORT_GPCHR_GPWE(0xFFFFUL); // Lockout unavailable pins
      PORTD->GPCLR = PinLock_Locked |0x0000UL|PORT_GPCLR_GPWE(0xFF00UL); // Lockout unavailable pins
      PORTD->GPCHR = PinLock_Locked |0x0000UL|PORT_GPCHR_GPWE(0xFFFFUL); // Lockout unavailable pins
      PORTE->GPCLR = PinLock_Locked |0x0000UL|PORT_GPCLR_GPWE(0xFFFCUL); // Lockout unavailable pins
      PORTE->GPCHR = PinLock_Locked |0x0000UL|PORT_GPCHR_GPWE(0xFFFFUL); // Lockout unavailable pins
   }

}
/**
 * End group USBDM_Group
 * @}
 */

} // End namespace USBDM

